@startuml

skinparam linetype ortho
!theme blueprint

entity config {
    *Id : String[4]
    ---
    *Key : String[30]
    *Value : String[50]
    ---
    *Created : String[19]
    *Updated : String[19]
}

entity GenKey {
    *Id : String[4]
    ---
    *Table : String[30]
    *Value : String[2]
    ---
    *Created : String[19]
    *Updated : String[19]
}

entity ImpStmt {
    *Id : String[4]
    ---
    *From : String[10]
    *To : String[10];
    *Account : String[20]
    *StmtType: Char;
    ---
    *Workflow : Char
    *Created : String[19]
    *Updated : String[19]
}

entity ImpTrans {
    *Id : String[4]
    ---
    *BookDate : String[10]
    *Desc : String[200]
    *Credit: String[12]
    *Debit: String[12]
    ---
    *Workflow: Char
    *ImpStmtId: String[4]
    *Created : String[19]
    *Updated : String[19]
}

ImpStmt ||--|{ ImpTrans

@enduml