# ------------------------------------------------------- #
# MyBudget - Make File                                    #
#                                                         #
# Copyright (c) 2026 James Dooley <james@dooley.ch>       #
#                                                         #
# 10/03/2026 - Initial Version                            #
# ------------------------------------------------------- #

default:
	@ECHO Commands: clean_bin, clean_db, clean_log, clean

clean_bin:
	-DEL ..\BIN\*.TPU
	-DEL ..\BIN\*.EXE
  -DEL ..\BIN\*.TPP

clean_db:
	-DEL ..\DATA\DB\*.*

clean_log:
	-DEL ..\DATA\LOGS\APP.LOG

clean:
	-DEL *.BAK
	-DEL *.TPU
	-DEL *.TPP



