(*--------------------------------------------------------*)
(*   SHARED.INC                                           *)
(*                                                        *)
(*   Copyright (C) 2026 James Dooley <james@dooley.ch>    *)
(*                                                        *)
(*   History                                              *)
(*   07/03/2026 - Initial Version                         *)
(*--------------------------------------------------------*)

const
	ERR_FAILED_TO_CREATE_TABLE		: Byte = 100;
  ERR_FAILED_TO_OPEN_TABLE			: Byte = 110;
  ERR_FAILED_TO_INSERT_SEED_DATA: Byte = 120;
  ERR_FAILED_TO_ADD_RECORD			:	Byte = 130;
  ERR_FAILED_TO_ADD_KEY					:	Byte = 140;
  ERR_GEN_KEY_MISSING						:	Byte = 150;
  ERR_FAILED_TO_ADD_REC         :	Byte = 160;
  ERR_FAILED_TO_LOAD_REC        :	Byte = 170;
  ERR_FAILED_TO_UPDATE_REC      :	Byte = 180;
  ERR_FAILED_TO_DELETE_REC      :	Byte = 190;
  ERR_CONFIG_FILE_NOT_FOUND     : Byte = 200;
